default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  port: 5432
  username: <%= ENV['DATABASE_USER'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>

development:
  <<: *default
  database: tnedo_dev

test: 
  <<: *default
  database: tnedo_test